### PR TITLE
Release 2.2.0

### PR DESCRIPTION
**Pull request by jayfunk**
PR to track the changes that are being worked on for version 2.2.0. 

First change thus far is to enable passcode fall back when FaceID or TouchID fails multiple times.

### CODE REVIEW

**Review by davidy3k — APPROVED** [review]

**Comment by saamerm** [comment]
Hey Thank you so much for the great work on this project!
Any timeline for this PR getting merged/next version going out?
We are having an issue in v68 of react native where the Android app started returning a null/undefined for `ReactNativeBiometrics.isSensorAvailable()`

**Comment by jayfunk** [comment]
There are a few other changes I am working to get into this release before it is merged and published. Hopefully by the end of the week I will have those changes resolved. Then maybe sometime next week I can cut the release. Have you checked to see if this release version of the package resolves your issue with your Android app?

**Comment by foxum** [comment]
Hi, could you also include Android device credentials support to next release?
It's implemented here https://github.com/SelfLender/react-native-biometrics/pull/147
Thanks for your work!

**Comment by jayfunk** [comment]
@foxum I have merged in Android device credential support. When you get a chance test it out and let me know if you run into any issues. The device credential support is limited to API 30 or greater. I updated the AndroidX Biometric library version to 1.1.0. 1.1.0 does not support Class 3 biometric hardware and device credentials for crypto based authentication in API versions prior to 30 (https://developer.android.com/reference/androidx/biometric/BiometricPrompt.PromptInfo.Builder#setAllowedAuthenticators(int)).

**Comment by jayfunk** [comment]
@saamerm Have you had a chance to test out this release version in your project?

**Review by davidy3k — APPROVED** [review]

**Review by davidy3k — COMMENTED** [review]
androidx.biometric version update looks good 👍

**Comment by sandergo90** [comment]
@dgasch512 @jayfunk do you have a time estimation about when the 2.2.0 release will be made public?

**Comment by jayfunk** [comment]
I am working on that currently. I looked at that PR and realized it would not work with the updated version of AndroidX biometrics. This functions are being deprecated and I figured it would be better to implement the newer standard. Should have it done sometime next week. 

Regards,
Tyler Cook

**Pull request merged**
