### PR TITLE
Added localisation for Android dialog

### PR DESCRIPTION
**Pull request by Peretz30**
Added 1 more object to pass in to functions to implement android localisation. #47

### CODE REVIEW

**Comment by YesSkyscrapers** [comment]
awesome, i faced this problem 10 minutes ago. U saved my day

**Comment by NappyPirate** [comment]
This should hopefully be resolved natively with in Android by the BiometricPrompt API

**Comment by sintylapse** [comment]
@NappyPirate is this issue fixed on native side? I changed language in emulator's settings, but nothing changed in prompt

**Comment by YesSkyscrapers** [comment]
@sintylapse it works fine for me. Check on real device. (eng <-> rus)

**Comment by sintylapse** [comment]
yes, thanks, the language was updated only when I used wrong finger print, so it caused text rerender i suppose

**Pull request closed without merging**
